server:
  port: 8081

spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/fraud_scanning_service_db"
    username: "postgres"
    password: "postgres"
  liquibase:
    change-log: file:./database/liquibase/db.changelog-master.yaml
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
